### PR TITLE
Added BellerophonTests scheme

### PR DESCRIPTION
**Pull request by JamesJSY**
@sagarnatekar @ThibaultKlein

### CODE REVIEW

**Comment by sagarnatekar** [comment]
👍

**Comment by ThibaultKlein** [comment]
@JamesJSY should we update the travis file to use the `BellerophonTests` scheme instead of `Bellerophon`?

**Comment by JamesJSY** [comment]
Yes, will do that

**Comment by JamesJSY** [comment]
Updated test schemes in travis.yml

**Comment by ThibaultKlein** [comment]
👍

**Pull request merged**
